apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:        # stringData lets you write plain text, kubernetes encodes it automatically
  DB_USER: "postgres"
  DB_PASS: "12345"